// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDlvRVlzYaIxHfqhEMM-8XOh26oOVkmAk',
    appId: '1:938287268907:android:db732f2b4877f20fda566e',
    messagingSenderId: '938287268907',
    projectId: 'restaurantapp-5c1be',
    storageBucket: 'restaurantapp-5c1be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBprawgNB3KjJngDgcUPuxAlB9HsbfDaf8',
    appId: '1:938287268907:ios:dbf8c81eac092d1cda566e',
    messagingSenderId: '938287268907',
    projectId: 'restaurantapp-5c1be',
    storageBucket: 'restaurantapp-5c1be.appspot.com',
    androidClientId: '938287268907-aruthfc38k9kj6svi9gcicvdaibjl0rl.apps.googleusercontent.com',
    iosClientId: '938287268907-lij6dn0fi8qnn62v9mioot713vpp5sfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );
}
